[package]
name = "activate"
description = "Environment activation CLI"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4", features=["derive"]}
toml = "0.8"
serde_json = "1"
serde = {version = "1", features=["derive"]}
ignore = "0.4"
num_cpus = "1"
crossbeam-channel = "0.5"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
dotenv = "0.15"