[package]
name = "activate"
description = "Environment activation CLI"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.11", features=["derive"]}
toml = "0.8.10"
serde = {version = "1.0.196", features=["derive"]}